### PR TITLE
Remove use of sha1

### LINKED ISSUE #49: Remove sha1 dependency.
We shouldn't use it, it's not needed.

### PR DESCRIPTION
**Pull request by steveno**
Fixes #49

### CODE REVIEW

**Comment by andrewchambers** [comment]
Thanks, this looks great. I will merge soon.

I'm still thinking if I can do something where I can store a shorter path on disk, but a full hash in the package database.

**Comment by steveno** [comment]
I don't know if it's related to this change or not but I got this error trying to compile the seed:

_truncated output_
```
'/home/steveno/.hermes/hermes-store/hpkg/a0c314a64c37a0bc367137f6f4c3e833428de80c-mcm-gcc/x86_64-linux-musl/lib/libatomic.la' -> '/home/steveno/.hermes/hermes-store/hpkg/227a75927077efbeb31e886c7078d144d1d7704a-new-seed/x86_64-linux-musl/lib/libatomic.la'
'/home/steveno/.hermes/hermes-store/hpkg/a0c314a64c37a0bc367137f6f4c3e833428de80c-mcm-gcc/x86_64-linux-musl/lib/libssp_nonshared.a' -> '/home/steveno/.hermes/hermes-store/hpkg/227a75927077efbeb31e886c7078d144d1d7704a-new-seed/x86_64-linux-musl/lib/libssp_nonshared.a'
'/home/steveno/.hermes/hermes-store/hpkg/a0c314a64c37a0bc367137f6f4c3e833428de80c-mcm-gcc/x86_64-linux-musl/lib/libatomic.a' -> '/home/steveno/.hermes/hermes-store/hpkg/227a75927077efbeb31e886c7078d144d1d7704a-new-seed/x86_64-linux-musl/lib/libatomic.a'
'/home/steveno/.hermes/hermes-store/hpkg/a0c314a64c37a0bc367137f6f4c3e833428de80c-mcm-gcc/x86_64-linux-musl/lib' -> '/home/steveno/.hermes/hermes-store/hpkg/227a75927077efbeb31e886c7078d144d1d7704a-new-seed/x86_64-linux-musl/lib'
'/home/steveno/.hermes/hermes-store/hpkg/a0c314a64c37a0bc367137f6f4c3e833428de80c-mcm-gcc/x86_64-linux-musl' -> '/home/steveno/.hermes/hermes-store/hpkg/227a75927077efbeb31e886c7078d144d1d7704a-new-seed/x86_64-linux-musl'
error: File exists: ./busybox -> strings
  in os/symlink
  in <anonymous> [/home/steveno/Projects/lisp/hpkgs/seed-out.hpkg] (tailcall) on line 17, column 7
  in do-build [src/pkgstore.janet] (tailcall) on line 506, column 23
error: builder failed
  in <anonymous> [src/pkgstore.janet] on line 515, column 17
  in run-builder [src/pkgstore.janet] on line 477, column 9
  in <anonymous> [src/pkgstore.janet] on line 458, column 21
  in build-pkg [src/pkgstore.janet] on line 449, column 17
  in build-pkg [src/pkgstore.janet] on line 445, column 36
  in <anonymous> [src/pkgstore.janet] on line 629, column 13
  in <anonymous> [src/pkgstore.janet] on line 433, column 3
  in <anonymous> [src/pkgstore.janet] on line 432, column 3
  in build [src/pkgstore.janet] on line 431, column 3
  in build [src/hermes-pkgstore-main.janet] on line 171, column 3
  in <anonymous> [src/hermes-pkgstore-main.janet] on line 288, column 19
  in main [src/hermes-pkgstore-main.janet] on line 285, column 3
```
I'm going to blow everything away and build it with the master branch and see what happens.

**Comment by andrewchambers** [comment]
May be a bug, I didn't add CI for seed_out as I didn't want to waste too much CPU for every commit, will have a look.

**Comment by andrewchambers** [comment]
@steveno fixed in https://github.com/andrewchambers/hpkgs/pull/115

**Pull request closed without merging**
